name = "v2ray-worker"
main = "index.js"
account_id = "bd89d9872587cdfedce7b62b016706b0"
workers_dev = true

kv_namespaces = [
  { binding = "V2RAY_STORE", id = "04374604780e4140b0b7ccdaff218afe" }
]

compatibility_date = "2025-06-16"
